data = [
    {'name': 'Instagram', 'follower': 346, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower': 215, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Taylor Swift', 'follower': 210, 'description': 'Singer-songwriter', 'country': 'United States'},
    {'name': 'Lionel Messi', 'follower': 184, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Kylie Jenner', 'follower': 365, 'description': 'Reality TV star and entrepreneur', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower': 242, 'description': 'Actor and former wrestler', 'country': 'United States'},
    {'name': 'Selena Gomez', 'follower': 208, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower': 355, 'description': 'Reality TV star and entrepreneur', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower': 210, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Shakira', 'follower': 144, 'description': 'Singer and dancer', 'country': 'Colombia'},
    {'name': 'Ariana Grande', 'follower': 270, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower': 238, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Emma Watson', 'follower': 84, 'description': 'Actress and activist', 'country': 'United Kingdom'},
    {'name': 'Justin Bieber', 'follower': 255, 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Will Smith', 'follower': 151, 'description': 'Actor and producer', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower': 107, 'description': 'Comedian and TV host', 'country': 'United States'},
    {'name': 'Zayn Malik', 'follower': 115, 'description': 'Singer', 'country': 'United Kingdom'},
    {'name': 'Kendall Jenner', 'follower': 241, 'description': 'Model and TV personality', 'country': 'United States'},
    {'name': 'Gigi Hadid', 'follower': 72, 'description': 'Model', 'country': 'United States'},
    {'name': 'Rihanna', 'follower': 116, 'description': 'Singer and entrepreneur', 'country': 'Barbados'},
    {'name': 'David Beckham', 'follower': 106, 'description': 'Footballer and entrepreneur', 'country': 'United Kingdom'},
    {'name': 'LeBron James', 'follower': 180, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Priyanka Chopra', 'follower': 120, 'description': 'Actress and producer', 'country': 'India'},
    {'name': 'Miley Cyrus', 'follower': 135, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Kourtney Kardashian', 'follower': 101, 'description': 'Reality TV star', 'country': 'United States'},
    {'name': 'Snoop Dogg', 'follower': 190, 'description': 'Rapper', 'country': 'United States'},
    {'name': 'Chris Hemsworth', 'follower': 71, 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Tom Hiddleston', 'follower': 78, 'description': 'Actor', 'country': 'United Kingdom'},
    {'name': 'BTS', 'follower': 330, 'description': 'K-pop group', 'country': 'South Korea'},
    {'name': 'Jimin', 'follower': 170, 'description': 'BTS member', 'country': 'South Korea'},
    {'name': 'Jungkook', 'follower': 159, 'description': 'BTS member', 'country': 'South Korea'},
    {'name': 'Suga', 'follower': 115, 'description': 'BTS member', 'country': 'South Korea'},
    {'name': 'Rosé', 'follower': 118, 'description': 'Blackpink member', 'country': 'New Zealand'},
    {'name': 'Lisa', 'follower': 112, 'description': 'Blackpink member', 'country': 'Thailand'},
    {'name': 'Jennie', 'follower': 127, 'description': 'Blackpink member', 'country': 'South Korea'},
    {'name': 'Jisoo', 'follower': 98, 'description': 'Blackpink member', 'country': 'South Korea'},
    {'name': 'Zac Efron', 'follower': 99, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Lady Gaga', 'follower': 212, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Kesha', 'follower': 78, 'description': 'Singer', 'country': 'United States'},
    {'name': 'Benedict Cumberbatch', 'follower': 74, 'description': 'Actor', 'country': 'United Kingdom'},
    {'name': 'Johnny Depp', 'follower': 65, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Lupita Nyong’o', 'follower': 50, 'description': 'Actress', 'country': 'Mexico'},
    {'name': 'Emma Stone', 'follower': 60, 'description': 'Actress', 'country': 'United States'},
    {'name': 'Shawn Mendes', 'follower': 89, 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Drake', 'follower': 168, 'description': 'Rapper and singer', 'country': 'Canada'},
    {'name': 'The Rock', 'follower': 240, 'description': 'Actor and wrestler', 'country': 'United States'},
    {'name': 'Adele', 'follower': 98, 'description': 'Singer', 'country': 'United Kingdom'},
    {'name': 'Kanye West', 'follower': 125, 'description': 'Rapper and entrepreneur', 'country': 'United States'},
    {'name': 'Eminem', 'follower': 142, 'description': 'Rapper', 'country': 'United States'},
    {'name': 'Billie Eilish', 'follower': 222, 'description': 'Singer', 'country': 'United States'},
    {'name': 'Lana Del Rey', 'follower': 82, 'description': 'Singer', 'country': 'United States'},
    {'name': 'Sofia Vergara', 'follower': 95, 'description': 'Actress', 'country': 'Colombia'},
    {'name': 'Rita Ora', 'follower': 56, 'description': 'Singer', 'country': 'United Kingdom'},
    {'name': 'Megan Thee Stallion', 'follower': 55, 'description': 'Rapper', 'country': 'United States'},
    {'name': 'Channing Tatum', 'follower': 48, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Kaitlyn Maher', 'follower': 45, 'description': 'Singer', 'country': 'United States'},
    {'name': 'Zac Efron', 'follower': 120, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Cameron Diaz', 'follower': 38, 'description': 'Actress', 'country': 'United States'},
    {'name': 'Gordon Ramsay', 'follower': 125, 'description': 'Chef and TV personality', 'country': 'United Kingdom'},
    {'name': 'Ariana DeBose', 'follower': 32, 'description': 'Actress', 'country': 'United States'},
    {'name': 'Matt Damon', 'follower': 74, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Vladimir Putin', 'follower': 35, 'description': 'Political figure', 'country': 'Russia'},
    {'name': 'Jackie Chan', 'follower': 100, 'description': 'Actor and martial artist', 'country': 'China'},
    {'name': 'Usain Bolt', 'follower': 48, 'description': 'Sprinter', 'country': 'Jamaica'},
    {'name': 'Messi', 'follower': 204, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Kylie Minogue', 'follower': 89, 'description': 'Singer', 'country': 'Australia'},
    {'name': 'Barack Obama', 'follower': 130, 'description': 'Former President', 'country': 'United States'},
    {'name': 'Michael Jordan', 'follower': 65, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Chris Evans', 'follower': 120, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Julia Roberts', 'follower': 38, 'description': 'Actress', 'country': 'United States'},
    {'name': 'Megan Fox', 'follower': 40, 'description': 'Actress', 'country': 'United States'},
    {'name': 'Dr. Phil McGraw', 'follower': 60, 'description': 'TV personality', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower': 350, 'description': 'Entrepreneur', 'country': 'United States'},
    {'name': 'Celine Dion', 'follower': 70, 'description': 'Singer', 'country': 'Canada'}
]
